name: Oncf Rest Api Pipeline

on:
  push:
    branches:
      - backend

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: List files
        run: ls

      - name: Print working directory
        run: pwd

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set execute permission for Maven wrapper
        run: sudo chmod +x ./mvnw

      - name: Verify permissions for Maven wrapper
        run: ls -l ./mvnw

      - name: Compile project
        run: ./mvnw clean compile

  build:
    runs-on: ubuntu-latest
    name: Build backend
    needs: [ compile ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set execute permission for Maven wrapper
        run: sudo chmod +x ./mvnw

      - name: Build project
        run: ./mvnw clean package -DskipTests
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set execute permission for Maven wrapper
        run: sudo chmod +x ./mvnw

      - name: Extract project version
        id: extract_version
        run: echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile  # Corrected path
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/oncf-rest-api:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKERHUB_USERNAME }}/oncf-rest-api:latest

  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Create deployment folder
        run: sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p /home/deeeler/oncf/RestApi"

      - name: Copy docker-compose file
        run: sshpass -p "${{ secrets.VPS_PASSWORD }}" scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:/home/deeeler/oncf/RestApi/docker-compose.yml

      - name: Copy Env file
        run: sshpass -p "${{ secrets.VPS_PASSWORD }}" scp -o StrictHostKeyChecking=no .env ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:/home/deeeler/oncf/RestApi/.env

      - name: Deploy
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          cd /home/deeeler/oncf/RestApi
          docker compose --env-file .env -f docker-compose.yml down || exit 1
          docker compose --env-file .env -f docker-compose.yml pull -q || exit 1
          docker compose --env-file .env -f docker-compose.yml up -d || exit 1
          EOF
